services:
  web:
    build: .
    container_name: mock_web
    env_file:
      - .env
    volumes:
      - .:/app 
      - sqlite_data:/app/data 
      - static_volume:/app/staticfiles
      - ./media:/app/media
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx_mock
    ports:
      - "8012:80"
    volumes:
      - static_volume:/static:ro
      - ./media:/media:ro
    depends_on:
      web:
        condition: service_started

volumes:
  sqlite_data:
  static_volume:
