# Generated by Django 5.2.8 on 2025-11-27 05:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('audio_file', models.FileField(upload_to='listening/audios/')),
                ('audio_duration', models.IntegerField(help_text='Duration in seconds')),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'listening_sections',
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('title', models.CharField(max_length=255)),
                ('passage_text', models.TextField(help_text='Full reading passage text')),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the passage', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_passages',
                'ordering': ['passage_number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('written', 'Written Answer'), ('options', 'Multiple Choice')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text="Required for 'options' type", null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.listeningsection')),
            ],
            options={
                'db_table': 'listening_questions',
                'ordering': ['question_number'],
                'unique_together': {('section', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('written', 'Written Answer'), ('options', 'Multiple Choice')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text="Required for 'options' type", null=True)),
                ('correct_answer', models.CharField(max_length=500)),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.readingpassage')),
            ],
            options={
                'db_table': 'reading_questions',
                'ordering': ['question_number'],
                'unique_together': {('passage', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='app.test'),
        ),
        migrations.AddField(
            model_name='listeningsection',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sections', to='app.test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('overall_band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('task_type', models.CharField(choices=[('data_description', 'Describe Data/Graph/Chart'), ('letter', 'Letter Writing'), ('essay', 'Essay'), ('report', 'Report')], max_length=50)),
                ('prompt_text', models.TextField(help_text='Task prompt/question')),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing/charts/')),
                ('instructions', models.TextField(blank=True)),
                ('word_limit', models.IntegerField(help_text='Minimum word count (150 or 250)')),
                ('time_suggestion', models.IntegerField(help_text='Suggested time in minutes (20 or 40)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='app.test')),
            ],
            options={
                'db_table': 'writing_tasks',
                'ordering': ['task_number'],
                'unique_together': {('test', 'task_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='readingpassage',
            unique_together={('test', 'passage_number')},
        ),
        migrations.AlterUniqueTogether(
            name='listeningsection',
            unique_together={('test', 'section_number')},
        ),
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.readingquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_answers', to='app.testattempt')),
            ],
            options={
                'db_table': 'reading_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent on this question in seconds')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listeningquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_answers', to='app.testattempt')),
            ],
            options={
                'db_table': 'listening_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField()),
                ('word_count', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('task_achievement', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('coherence_cohesion', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('lexical_resource', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('grammatical_accuracy', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='app.testattempt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_writings', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.writingtask')),
            ],
            options={
                'db_table': 'writing_submissions',
                'unique_together': {('attempt', 'task')},
            },
        ),
    ]
