# Generated by Django 5.2.8 on 2025-12-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingpassage',
            name='source',
        ),
    ]
