# Generated by Django 5.2.8 on 2025-12-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_readingpassage_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingquestion',
            name='points',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
